version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: localhost
    ports:
    - "443:443"
    - "80:80"
    - "2222:22"
    volumes:
    - gitlab_config:/etc/gitlab
    - gitlab_logs:/var/log/gitlab
    - gitlab_data:/var/opt/gitlab
    restart: always
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: