version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: gitlab
    ports:
    - "443:443"
    - "80:80"
    - "2222:22"
    volumes:
    - gitlab_config:/etc/gitlab
    - gitlab_logs:/var/log/gitlab
    - gitlab_data:/var/opt/gitlab
    restart: always
  runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - gitlab_runner_config:/etc/gitlab-runner:Z
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:
