name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: npm install && npm run build
      uses: docker://node:16-alpine
    with:
      name: artifact
      path: |
        dist

