name: GitHub Actions Demo
on: [push]
jobs:
  build-react-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./store
    container:
      image: node:16-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: pwd && ls && npm install && npm run build
    - name: react-artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          store/dist
  deploy-react-app:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli
    needs: build-react-app
    steps:
    - name: Download dist folder
      uses: actions/download-artifact@v3
      with:
        name: dist-without-markdown
    - run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_DEFAULT_REGION=us-east-1
        aws s3 sync --delete ./ s3://artyom-aca-test

