name: GitHub Actions Demo
on: [push]
jobs:
  build-react-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./store
    container:
      image: node:16-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
    - run: pwd && ls && npm install && npm run build
    - name: react-artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          store/dist
  deploy-react-app:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli
    needs: build-react-app
    steps:
    - name: Download dist folder
      uses: actions/download-artifact@v3
      with:
        name: dist-without-markdown
    - run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws s3 sync --delete ./ s3://artyom-aca-test

